name: hocon
version: 0.1.0.2
github: "aleperaltabazas/hocon"
license: BSD3
author: "Alejandro Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2020 Alejandro Peralta Bazas"

extra-source-files:
    - README.md
    - ChangeLog.md

synopsis: Small library for typesafe's configuration specification
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Small library for typesafe's configuration specification

dependencies:
    - base >= 4.7 && < 5
    - hspec
    - MissingH <= 1.4.3.0
    - parsec <= 3.1.14.0
    - split <= 0.2.3.4

library:
    source-dirs: src

executables:
    hocon-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - hocon

tests:
    hocon-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - hocon
